# Generated by Django 3.2.8 on 2021-10-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='', max_length=20)),
                ('device_type', models.CharField(choices=[('sensor', 'sensor'), ('actuator', 'actuator')], max_length=10)),
                ('device_model', models.CharField(default='', max_length=30)),
                ('last_updated', models.DateField(auto_now=True)),
                ('registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
