# Generated by Django 3.2.7 on 2021-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0004_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='modified_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Following', 'Following')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devices',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
