# Generated by Django 3.2.7 on 2021-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0005_auto_20211204_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Following', 'Following'), ('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete')], max_length=20),
        ),
    ]
