# Generated by Django 3.2.7 on 2021-12-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0007_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_character',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Fox', 'Fox'), ('Lion', 'Lion'), ('Penguin', 'Penguin'), ('Wolf', 'Wolf')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
